GET http://127.0.0.1:5173/api/components HTTP/1.1
content-type: application/json
accept: application/json
Cookie: next-auth.csrf-token=40007cba6453551312e2b0fbdbd7d9e7c0afd3ce73a41a88b03c084fc1da04b7%7C601b606ccad721197c8b3c493bb30befca54440402dc4795f2a7b72200219d0a; next-auth.callback-url=http%3A%2F%2Flocalhost%3A5173%2Flogin; next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..8h4Cwg2FhBElFyDR.wyhySrdweFT8ySmH3ookQcxxT_9gLZNpJe5JZdyhv4UApE4A24wkHz1mSjBr1K6ySNdTZ7juOroy7XR5bWJ3YKQQqTOE3fi6El_tL01aEJXUEKoAojBzJaToaP_hvh0PX4MvQLRnVXNBpN59fed8A1UZoW57Bc2nvg28aPZKXhmVjdCsjfvygasGOkJanlokjaNgFA2DyLGNK33yOacKAQSUoHBJg0uh-hcIyTGA94qRygN7FpqBaMSP5XqK3vs64oa1WQJf_yap-WHXUOhY4hJU.gjIrMyo8sVQmqR2hB6Lcsg

###
GET https://smart-nudging-engine.vercel.app/api/components HTTP/1.1
content-type: application/json
accept: application/json
Cookie: __Host-next-auth.csrf-token=c31fef8438ce585960e306024f4506f55fdfd015d06da198a7cc7464ac3c423a%7C8dea9f5c2279d305b1577fdb6c88de09a5d918afeb2cffdf447710454556b052; __Secure-next-auth.callback-url=https%3A%2F%2Fsmart-nudging-engine.vercel.app%2Flogin; __Secure-next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..HuoNGzjUagcMmV-8.fTb--Ru5b-ngM886EJs_um9GhkhoDUtFpRG_CoBpU_CPmukhSyySTmnuzJ5Klve8Omcs6uOP1h5pV_RGRtfSwCU_HWP12XJQVzpW5ULnmDQ0tjZ9j8EzrvjZ8I4MIxl57FB7W5QOmR-XgE-SZ94kyB48NB8H1KaB1_LJyCYbpvBVRDVckI0LHmOdM2611mGBf53z3Ba9filoC2rkGbOKpPRc4abFZafFc4H3GsULix87--WcS4KT7WrJd8fh3t8CHKTaQ15zVmP6xIcQoyTlTgC5.aO7a8qHOGCMQePcTkSazDA